version: '3.1'

services:

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app:app@postgres:5432/db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app
    links:
      - postgres:postgres

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/db?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - ./db:/var/lib/postgresql/data
